<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8359" started-at="2019-03-19T18:14:33Z" finished-at="2019-03-19T18:14:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8359" started-at="2019-03-19T18:14:33Z" finished-at="2019-03-19T18:14:41Z">
      <class name="assignment.userDetails">
        <test-method status="PASS" signature="GetMethod()[pri:1, instance:assignment.userDetails@724af044]" name="GetMethod" duration-ms="5188" started-at="2019-03-19T18:14:33Z" finished-at="2019-03-19T18:14:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetMethod -->
        <test-method status="PASS" signature="PostMethod()[pri:2, instance:assignment.userDetails@724af044]" name="PostMethod" duration-ms="936" started-at="2019-03-19T18:14:38Z" finished-at="2019-03-19T18:14:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostMethod -->
        <test-method status="FAIL" signature="PutMethod()[pri:3, instance:assignment.userDetails@724af044]" name="PutMethod" duration-ms="2181" started-at="2019-03-19T18:14:39Z" finished-at="2019-03-19T18:14:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at assignment.userDetails.PutMethod(userDetails.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PutMethod -->
      </class> <!-- assignment.userDetails -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
